name: semirings
version: "0.1"
license: "GPL-2.0-or-later"
date: 2025-03-12
description: |
    Enumerate semirings

authors:
    - name: James Mitchell
      url: https://jdbm.me
    - name: Pramoth Ragavan
      url: https://pramothragavan.github.io/

maintainers:
    - name: James Mitchell
      url: https://jdbm.me
    - name: Pramoth Ragavan
      url: https://pramothragavan.github.io/

GAP: ">= 4.13"

needed-pkgs:
    - name: "semigroups"
      version: ">= 5.5"
      url: "https://semigroups.github.io/Semigroups"
    - name: "smallsemi"
      version: ">= 0.7.2"
      url: "https://gap-packages.github.io/smallsemi/"

www: https://pramothragavan.github.io/semirings/
readme: README.md
packageinfo: https://pramothragavan.github.io/semirings/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/pramothragavan/semirings/releases/download/v0.1/semirings-0.1.tar.gz

abstract: |

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MR25</span>]   <b class='BibAuthor'>Mitchell, J. and Ragavan, P.</b>,
     <i class='BibTitle'>semirings, Enumerate semirings,
             Version 0.1</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://pramothragavan.github.io/semirings/">https://pramothragavan.github.io/semirings/</a></span>.
    </p>
    

bibtex: |
    @misc{ semirings,
      author =           {Mitchell, J. and Ragavan, P.},
      title =            {{semirings}, Enumerate semirings, {V}ersion 0.1},
      month =            {Mar},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href    {https://pramothragavan.github.io/semirings/}
                          {\texttt{https://pramothragavan.github.io/}\discretionary
                          {}{}{}\texttt{semirings/}}},
      printedkey =       {MR25}
    }

